services:
  mysql:
    container_name: mysql-booknetwork_api
    image: mysql:latest
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: book_network
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - book
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  book:
    driver: bridge

volumes:
  mysql:
    driver: local
